### ISSUE TITLE
Show files inside zip with correct mtime/ctime

### ISSUE THREAD

**Issue by JuniorJPDJ** [openscopeproject/ZipROFS#5]
ATM ZipROFS shows files inside ZIP with same ctime/mtime as ctime/mtime of ZIP file.
ZIP file itself holds ctime of files inside ZIP which IMO should be used.
I added this as TODO comment in #4, but forgot to do this: https://github.com/openscopeproject/ZipROFS/blob/1b05d8471ff8a6e4a0b4a364ef63b2104519ca60/ziprofs.py#L123
The question here is if we should to use it as ctime, mtime or both (I personaly would go with both).

**Comment by qu1ck** [comment]
I think we should only touch mtime. Otherwise more logic is needed to calculate direcotry mtime as max of ctime of files in it.
If we keep all ctimes as zip file's ctime and only set mtime of files there will be no inconsistencies.

**Comment by JuniorJPDJ** [comment]
I'm not sure if every app will behave predictably with ctime > mtime - and that will be our case most of time.

**Comment by qu1ck** [comment]
It's normal for ctime to be after mtime. ctime is not creation time, it's metadata change time.

**Comment by JuniorJPDJ** [comment]
Oh.
I was pretty sure it's creation time.
It's good then, you are right :D 
I'm closing this, as you resolved issue.

**Comment by JuniorJPDJ** [comment]
BTW it seems like there's sometimes also time on directory inside zip:
![Screenshot_20200831_022237](https://user-images.githubusercontent.com/7334549/91672811-d9028500-eb30-11ea-97f3-99b35fe4b921.png)
I'm not sure what it depends on, but I wasn't doing any research, just noticed it when opening zips.

**Comment by qu1ck** [comment]
Zip file format does not support directory entries, only files. Some archivers put an empty `.` file for each subdirectory but it's not required.

**Comment by JuniorJPDJ** [comment]
That makes sense why one of zips have meta on directories and other doesn't.
What do you think about supporting this `.` files in this case?

**Comment by JuniorJPDJ** [comment]
![image](https://user-images.githubusercontent.com/7334549/91791590-d3ca3680-ec13-11ea-80d7-f755e674ce5a.png)
It doesn't work.
Look at date selected in terminal and date of the same dir in Ark window (selected one).

**Comment by qu1ck** [comment]
Your command prompt suggest you are 2 commits behind. Did you pull the changes?

**Comment by JuniorJPDJ** [comment]
..well
I did..
On other PC..
Thanks, it works as intended >__<

**Comment by qu1ck** [comment]
If you feel like contributing more, I noticed a bug where returned timestamp is not in the right timezone. I.e. time in 7zip for me shows some hours ahead of what I see in ziprofs mounted folder. I didn't investigate this further, feel free to take a look.

**Comment by JuniorJPDJ** [comment]
We probably should open issue for that, so noone will forget about it :D 
I'm now doing other things, but maybe some day..
